### ISSUE TITLE
支持语雀空间

### ISSUE THREAD

**Issue by sdhjl2000** [vannvan/yuque-tools#10]
有独立域名的语雀空间的导出

**Comment by vannvan** [comment]
> 有独立域名的语雀空间的导出

空间可以有，但是独立域名我不清楚具体的API和权限机制共有的有没有区别

**Comment by vannvan** [comment]
> > 有独立域名的语雀空间的导出
> 
> 空间可以有，但是独立域名我不清楚具体的API和权限机制共有的有没有区别

2023.07.15 @2.0版本已支持

**Comment by tookbra** [comment]
> > > 有独立域名的语雀空间的导出
> > 
> > 
> > 空间可以有，但是独立域名我不清楚具体的API和权限机制共有的有没有区别
> 
> 2023.07.15 @2.0版本已支持

crawlYuqueBookPage这个方法
window.appData.book 返回undefined 看了下确实没有book 获取不到文档,  但是在真实游览器中控制台却可以打印出来

**Comment by vannvan** [comment]
> 

有可能是访问语雀对应知识库的页面失败了，有没有重试过呢，情况比较复杂的话可以加我v信 base64 MTc3ODI1MjQ4NjI=
