### ISSUE TITLE
pull 命令不存在

### ISSUE THREAD

**Issue by lululutx** [vannvan/yuque-tools#13]
作者您好，install安装后显示pull不存在。node版本 18.0.0，终端已使用管理员模式，代理与否均已尝试，npm安装和cnpm均已尝试。

![image](https://github.com/vannvan/yuque-tools/assets/48202120/842cbb13-4091-48be-a5fa-0ec2e131ff53)

**Comment by vannvan** [comment]
不好意思，现在才看到，`glob`在`windows`有点问题，我明天修复下

**Comment by vannvan** [comment]
> 作者您好，install安装后显示pull不存在。node版本 18.0.0，终端已使用管理员模式，代理与否均已尝试，npm安装和cnpm均已尝试。
> 
> ![image](https://user-images.githubusercontent.com/48202120/255933230-842cbb13-4091-48be-a5fa-0ec2e131ff53.png)

**Comment by vannvan** [comment]
已修复，需要下载2.0.2版本

**Comment by lululutx** [comment]
感谢！第一时间尝试了下，完全没问题
