### ISSUE TITLE
能导出收藏的文章吗 

### ISSUE THREAD

**Issue by ivoidcat** [vannvan/yuque-tools#19]

**Comment by vannvan** [comment]
> _No description provided._

技术上来讲是可以的

**Comment by ivoidcat** [comment]
现在主要的痛点就是没法保存他人的，万一哪天打不开了，收藏的也没用了，比如
https://www.yuque.com/u589148/sc

**Comment by vannvan** [comment]
> 现在主要的痛点就是没法保存他人的，万一哪天打不开了，收藏的也没用了，比如 https://www.yuque.com/u589148/sc

虽然工具比较简单其实也具备为所欲为的能力，但是这种功能之所以没做的原因有三点：
1. 这项能力本质属于导出他人的知识库，若被滥用在一定程度上是违背道义的；
2. 目前从技术上能实现仅仅是语雀的一个漏洞，如果做了就避免不了被目的不单纯的人滥用，也是违背我个人做这个工具的初衷的，见 [关于](https://github.com/vannvan/yuque-tools/blob/main/ABOUT.md)；
3. 导出会携带cookie，记录应该会被语雀检测到，会不会导致封号也是不确定的

如果确实有这样的需求的话，可以fork，稍加改造就可以实现，感谢支持！

**Comment by ivoidcat** [comment]
好感谢回复，我来研究下

**Comment by ivoidcat** [comment]
感谢作者的贡献，已经搞定了。
