### ISSUE TITLE
win64  nodejs下载语雀文档失败，本地只建了目录里面内容是空的

### ISSUE THREAD

**Issue by maokingcs** [vannvan/yuque-tools#21]
错误信息：ERR_BAD_REQUEST    👉提个bug (​https://github.com/vannvan/yuque-tools/issues/new​)

截图如下
![微信图片_20230907003701](https://github.com/vannvan/yuque-tools/assets/143875351/cad173e6-6e59-4276-8ba4-d09c8638953f)

**Comment by vannvan** [comment]
> 错误信息：ERR_BAD_REQUEST 👉提个bug (​[https://github.com/vannvan/yuque-tools/issues/new​](https://github.com/vannvan/yuque-tools/issues/new%E2%80%8B))
> 
> 截图如下 ![微信图片_20230907003701](https://user-images.githubusercontent.com/143875351/266079144-cad173e6-6e59-4276-8ba4-d09c8638953f.png)

看到有导出9个文件，这9个文件也不存在吗？ERR_BAD_REQUET 有没有尝试重试呢？
