### ISSUE TITLE
差异备份功能是否能实现

### ISSUE THREAD

**Issue by lonelyvaf** [vannvan/yuque-tools#24]
因为语雀的定位变了，但不妨碍它是一个很好的知识库工具。要定期备份且将更新变化的内容发到博客上。用工具的话一旦我内容发生了变化不就一直重复导出吗？

**Comment by vannvan** [comment]
> 因为语雀的定位变了，但不妨碍它是一个很好的知识库工具。要定期备份且将更新变化的内容发到博客上。用工具的话一旦我内容发生了变化不就一直重复导出吗？

可以理解为每次只“导出”此次发生变更的文档吗？

**Comment by lonelyvaf** [comment]
是的，而且我发现只导出md文件的话，都其他一些office文件不是太友好，比如：excel。导出来的内容是有问题的。

**Comment by vannvan** [comment]
> 是的，而且我发现只导出md文件的话，都其他一些office文件不是太友好，比如：excel。导出来的内容是有问题的。

感谢提议，不过差异性备份可能没那么快能过实现，关于只支持Markdown文件的说明见 [特别说明](https://github.com/vannvan/yuque-tools/blob/main/ABOUT.md#%E7%89%B9%E5%88%AB%E8%AF%B4%E6%98%8E)
