### ISSUE TITLE
error：选择出错，请重新尝试

### ISSUE THREAD

**Issue by nanchenboy** [vannvan/yuque-tools#26]
获取知识库成功后
thread 'main' panicked at src/libs/inquiry.rs:49:27:
选择出错，请重新尝试
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by vannvan** [comment]
> inquiry.rs:49:27:

需要空格选中具体的知识库，选中的话列表前面会有叉叉，确认一下呢
