### ISSUE TITLE
pull 命令不存在，请使用 -h 查看有效命令

### ISSUE THREAD

**Issue by linglong117** [vannvan/yuque-tools#27]
mac 下面 执行  ytool pull/clear 等命令是 提示命令不存在

**Comment by vannvan** [comment]
> mac 下面 执行 ytool pull/clear 等命令是 提示命令不存在

如果是程序版，前面是需要 ./ 的

> ./ytool pull

**Comment by linglong117** [comment]
我是非程序版运行的  npm i yuque-tools -g 安装到全局 
你好，程序版的怎么运行，前端代码不熟

**Comment by vannvan** [comment]
> 我是非程序版运行的 npm i yuque-tools -g 安装到全局 你好，程序版的怎么运行，前端代码不熟

那尝试一下程序版呢 [程序版地址](https://github.com/vannvan/yuque-tools/releases/tag/v1.0.0-beta)，参照【打开方式】进行导出

**Comment by linglong117** [comment]
mac  intel  执行报  zsh: bad CPU type in executable: ./ytool  ；
用 windows 版  报如下错 
thread 'main' panicked at src/libs/tools.rs:69:49:
知识库文件解析失败: Error("invalid type: null, expected a sequence", line: 1, column: 452)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by vannvan** [comment]
> mac intel 执行报 zsh: bad CPU type in executable: ./ytool ； 用 windows 版 报如下错 thread 'main' panicked at src/libs/tools.rs:69:49: 知识库文件解析失败: Error("invalid type: null, expected a sequence", line: 1, column: 452) note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

看一下操作目录下 .meta/books_info.json 文件的内容是否形如以下格式: 

```json
{
  "books_info":[{
    "book_id": 20670941,
      "book_type": "owner",
      "docs": [
        {
          "child_uuid": "CO"
          //省略其它
          }
        ]
  },{
    //省略其它
  }],
  "expire_time": 1698233929635
}
```
不是以上内容格式的话 ytool clear 再重新试一下呢

如果还是不行加一下我[wx](https://github.com/vannvan/yuque-tools/issues/15)
