### ISSUE TITLE
pull之后还未选择就报错

### ISSUE THREAD

**Issue by zhangjie93** [vannvan/yuque-tools#30]
## 设备信息

win11 64位

## 操作步骤

登录成功后未选择知识库就报错

### 实际发生的

ytool-> 登录成功!
ytool-> 开始获取知识库
ytool-> 获取知识库成功
thread 'main' panicked at src/libs/inquiry.rs:49:27:
选择出错，请重新尝试
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### 期望的

--

**Comment by vannvan** [comment]
> ## 设备信息
> win11 64位
> 
> ## 操作步骤
> 登录成功后未选择知识库就报错
> 
> ### 实际发生的
> ytool-> 登录成功! ytool-> 开始获取知识库 ytool-> 获取知识库成功 thread 'main' panicked at src/libs/inquiry.rs:49:27: 选择出错，请重新尝试 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> ### 期望的
> --

确认一下在pull等待片刻之后是否有出现待选列表，如下
<img width="347" alt="image" src="https://github.com/vannvan/yuque-tools/assets/43501134/84bf96e5-6e1a-4526-b420-1f52c334e2fd">
**选择出错，请重新尝试** 这个报错只会在待选时手动退出了才会出现
