### ISSUE TITLE
知识库列表没有团队的知识库，请问如何拉团队的知识库

### ISSUE THREAD

**Issue by iAmCorey** [vannvan/yuque-tools#33]
## 设备信息

如：mac m1pro

## 操作步骤

使用 npx ytool pull 出来的知识库都是个人的

### 实际发生的

 请选择知识库(空格选中,a选中所有) (Press <space> to select, <a> to toggle all,
<i> to invert selection, and <enter> to proceed)
❯◯ 👥[1]个人
 ◯ 👥[2]上班摸鱼下班
 ◯ 👥[3]银行打工人
 ◯ 👥[4]Next.js学习(node:15640) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

--

### 期望的

实际上这四个知识库是我个人的知识库，不是团队的知识库，团队的一个都没展示出来

--

**Comment by vannvan** [comment]
> ## 设备信息
> 如：mac m1pro
> 
> ## 操作步骤
> 使用 npx ytool pull 出来的知识库都是个人的
> 
> ### 实际发生的
> 请选择知识库(空格选中,a选中所有) (Press to select, to toggle all, to invert selection, and to proceed) ❯◯ 👥[1]个人 ◯ 👥[2]上班摸鱼下班 ◯ 👥[3]银行打工人 ◯ 👥[4]Next.js学习(node:15640) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead. (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> --
> 
> ### 期望的
> 实际上这四个知识库是我个人的知识库，不是团队的知识库，团队的一个都没展示出来
> 
> --

确认配置是否如下格式:
```json
{
  "userName": "",
  "password": "",
  "host": "xxx",
  "skipDoc": true,
  "linebreak": false
}
```
`ytool clear`之后，再重新`pull`试一下呢
