### ISSUE TITLE
最好能有合并一个项目的多个文档到一个文档的功能，有的教程都分成了几百个小文档，合并之后方便打印

### ISSUE THREAD

**Issue by tomorrowqcm** [vannvan/yuque-tools#34]
## 使用的工具

> 在以下`[]`中输入`x`即可

- [] Node.js环境的CLI
- [] 浏览器插件
- [] 可执行程序

## 建议

> 例如：希望浏览器端可以有更好的给文章打标签的功能，因为语雀做的操作步骤太麻烦了

**Comment by vannvan** [comment]
不能考虑做哈，原因如下：
1. 合并文档不属于**导出yuque知识库**的范畴，脱离了该工具的边界
2. “合并一个项目的多个文档”即存在部分文档需求的可能，就复杂了～

推荐以下工具[在线合并Markdown](https://products.fileformat.app/zh/word-processing/merger)
