### ISSUE TITLE
能不能导出搜藏的知识库

### ISSUE THREAD

**Issue by SiMaLaoShi** [vannvan/yuque-tools#35]
## 使用的工具

> 在以下`[]`中输入`x`即可

- [] Node.js环境的CLI
- [] 浏览器插件
- [] 可执行程序

## 建议

> 例如：希望浏览器端可以有更好的给文章打标签的功能，因为语雀做的操作步骤太麻烦了

**Comment by vannvan** [comment]
[见这里](https://github.com/vannvan/yuque-tools/blob/main/packages/yuque-tools-cli/src/command/down.ts#L20)

**Comment by SiMaLaoShi** [comment]
> [见这里](https://github.com/vannvan/yuque-tools/blob/main/packages/yuque-tools-cli/src/command/down.ts#L20)

编译出来的exe不能用吗，我看下error: unrecognized subcommand 'down'

**Comment by SiMaLaoShi** [comment]
> Owner

牛逼搞定了，但是有些好像有问题，
![image](https://github.com/vannvan/yuque-tools/assets/28924681/90761aa4-3aa2-4a90-b53a-037c1a81cb58)
ETIMEDOUT    👉提个BUG(cmd/ctrl+click) (​https://github.com/vannvan/yuque-tools/issues/new?title=Error%E4%B8%8A%E6%8A%A5%2FGET%E8%AF%B7%E6%B1%82%E5%87%BA%E9%94%99&body=Node%3A+18.16.0+OS%3A+win32%0A%E9%94%99%E8%AF%AF%E4%BF%A1%E6%81%AF%3A+Error%3A+connect+ETIMEDOUT+139.224.214.226%3A443%2Chttps%3A%2F%2Fwww.yuque.com%2Fduing-qttf3%2Ffg7n3i%0AError%0A++++at+Object.error+%28file%3A%2F%2F%2FC%3A%2FUsers%2Fhuangwei%2FAppData%2FRoaming%2Fnpm%2Fnode_modules%2Fyuque-tools%2Fdist%2Flib%2Fdev%2Flog.js%3A8%3A27%29%0A++++at+file%3A%2F%2F%2FC%3A%2FUsers%2Fhuangwei%2FAppData%2FRoaming%2Fnpm%2Fnode_modules%2Fyuque-tools%2Fdist%2Flib%2Frequest.js%3A63%3A17%0A++++at+process.processTicksAndRejections+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A95%3A5%29%0A%0A%E4%BB%A5%E4%B8%8A%E4%BF%A1%E6%81%AF%E5%8F%AF%E5%88%A0%E9%99%A4%E8%B7%AF%E5%BE%84%E7%AD%89%E9%9A%90%E7%A7%81%E4%BF%A1%E6%81%AF%EF%BC%8C%E4%BD%86%E9%9C%80%E8%A6%81%E4%BF%9D%E7%95%99%E4%B9%8B%E5%90%8E%E7%9A%84%E8%A1%8C%E6%95%B0%E5%93%A6%7E​)
知识库/duing-qttf3/fg7n3i页面数据爬取失败

**Comment by vannvan** [comment]
> > Owner
> 
> 牛逼搞定了，但是有些好像有问题， ![image](https://private-user-images.githubusercontent.com/28924681/308062782-90761aa4-3aa2-4a90-b53a-037c1a81cb58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTc3MTYsIm5iZiI6MTcwOTAxNzQxNiwicGF0aCI6Ii8yODkyNDY4MS8zMDgwNjI3ODItOTA3NjFhYTQtM2FhMi00YTkwLWI1M2EtMDM3YzFhODFjYjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA3MDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwOGVkODRkYzE5MzE3NWZlMDAxNzc1ODViYmZkZmNlMGVmM2ZiOWQyNjVkNzYwY2Q3ZjY5MjZlNDYzOWNjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cTtUR2aSyGRFbBygD0DcruwxfRChcWBiyULpQMV2UAc) ETIMEDOUT 👉提个BUG(cmd/ctrl+click) (​[https://github.com/vannvan/yuque-tools/issues/new?title=Error%E4%B8%8A%E6%8A%A5%2FGET%E8%AF%B7%E6%B1%82%E5%87%BA%E9%94%99&body=Node%3A+18.16.0+OS%3A+win32%0A%E9%94%99%E8%AF%AF%E4%BF%A1%E6%81%AF%3A+Error%3A+connect+ETIMEDOUT+139.224.214.226%3A443%2Chttps%3A%2F%2Fwww.yuque.com%2Fduing-qttf3%2Ffg7n3i%0AError%0A++++at+Object.error+%28file%3A%2F%2F%2FC%3A%2FUsers%2Fhuangwei%2FAppData%2FRoaming%2Fnpm%2Fnode_modules%2Fyuque-tools%2Fdist%2Flib%2Fdev%2Flog.js%3A8%3A27%29%0A++++at+file%3A%2F%2F%2FC%3A%2FUsers%2Fhuangwei%2FAppData%2FRoaming%2Fnpm%2Fnode_modules%2Fyuque-tools%2Fdist%2Flib%2Frequest.js%3A63%3A17%0A++++at+process.processTicksAndRejections+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A95%3A5%29%0A%0A%E4%BB%A5%E4%B8%8A%E4%BF%A1%E6%81%AF%E5%8F%AF%E5%88%A0%E9%99%A4%E8%B7%AF%E5%BE%84%E7%AD%89%E9%9A%90%E7%A7%81%E4%BF%A1%E6%81%AF%EF%BC%8C%E4%BD%86%E9%9C%80%E8%A6%81%E4%BF%9D%E7%95%99%E4%B9%8B%E5%90%8E%E7%9A%84%E8%A1%8C%E6%95%B0%E5%93%A6%7E​](https://github.com/vannvan/yuque-tools/issues/new?title=Error%E4%B8%8A%E6%8A%A5%2FGET%E8%AF%B7%E6%B1%82%E5%87%BA%E9%94%99&body=Node%3A+18.16.0+OS%3A+win32%0A%E9%94%99%E8%AF%AF%E4%BF%A1%E6%81%AF%3A+Error%3A+connect+ETIMEDOUT+139.224.214.226%3A443%2Chttps%3A%2F%2Fwww.yuque.com%2Fduing-qttf3%2Ffg7n3i%0AError%0A++++at+Object.error+%28file%3A%2F%2F%2FC%3A%2FUsers%2Fhuangwei%2FAppData%2FRoaming%2Fnpm%2Fnode_modules%2Fyuque-tools%2Fdist%2Flib%2Fdev%2Flog.js%3A8%3A27%29%0A++++at+file%3A%2F%2F%2FC%3A%2FUsers%2Fhuangwei%2FAppData%2FRoaming%2Fnpm%2Fnode_modules%2Fyuque-tools%2Fdist%2Flib%2Frequest.js%3A63%3A17%0A++++at+process.processTicksAndRejections+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A95%3A5%29%0A%0A%E4%BB%A5%E4%B8%8A%E4%BF%A1%E6%81%AF%E5%8F%AF%E5%88%A0%E9%99%A4%E8%B7%AF%E5%BE%84%E7%AD%89%E9%9A%90%E7%A7%81%E4%BF%A1%E6%81%AF%EF%BC%8C%E4%BD%86%E9%9C%80%E8%A6%81%E4%BF%9D%E7%95%99%E4%B9%8B%E5%90%8E%E7%9A%84%E8%A1%8C%E6%95%B0%E5%93%A6%7E%E2%80%8B)) 知识库/duing-qttf3/fg7n3i页面数据爬取失败

我看了下知识库，有几个文档不是markdown类型的，还有没有开放权限只能看到目录的，只要是页面可正常访问的都可以导出，后续会加对应的容错～
