### ISSUE TITLE
Error上报/GET请求出错

### ISSUE THREAD

**Issue by otkinlife** [vannvan/yuque-tools#36]
Node: 16.20.2 OS: linux
错误信息: AxiosError: Request failed with status code 404,https://www.yuque.com/jiaxiaohua-77snn/iu463b/bugrotgdp2pfvcan/markdown?attachment=true&latexcode=false&anchor=false&linebreak=false
Error
    at Object.error (file:///.../yuque-tools/dist/lib/dev/log.js:8:27)
    at file:///.../yuque-tools/dist/lib/request.js:63:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

以上信息可删除路径等隐私信息，但需要保留之后的行数哦~

同步的时候遇到报错，我发现报错的文档类型都是表格类型的文档

**Comment by vannvan** [comment]
> Node: 16.20.2 OS: linux 错误信息: AxiosError: Request failed with status code 404,https://www.yuque.com/jiaxiaohua-77snn/iu463b/bugrotgdp2pfvcan/markdown?attachment=true&latexcode=false&anchor=false&linebreak=false Error at Object.error (file:///.../yuque-tools/dist/lib/dev/log.js:8:27) at file:///.../yuque-tools/dist/lib/request.js:63:17 at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> 以上信息可删除路径等隐私信息，但需要保留之后的行数哦~
> 
> 同步的时候遇到报错，我发现报错的文档类型都是表格类型的文档

是这样的没错，工具只能导出markdown类型的文档，其它类型的不具备可迁移能力。
