### ISSUE TITLE
感谢大佬，终于解决了语雀下载的问题。但是希望改进一下

### ISSUE THREAD

**Issue by walker83** [vannvan/yuque-tools#4]
有几类文档无法导出
1.表格型数据
2. 嵌入附件的文档
3. 其他语雀定义的比较复杂的格式

1. 因为有读取不了的场景，这个时候就会直接报错，导致中断，希望能够增加异常处理
rror: ENOENT: no such file or directory, open './docs/xxxx.md'
    at Object.openSync (node:fs:590:3)
    at Object.writeFileSync (node:fs:2295:35)
    at File.touch2 (file:///usr/local/lib/node_modules/yuque-tools/dist/lib/file.js:57:12)
    at Timeout._onTimeout (file:///usr/local/lib/node_modules/yuque-tools/dist/lib/tool.js:245:15)

还有
请选择知识库(空格选中--这个是有文件嵌入的
⠦ 正在导出[xxxxx/it/bi92pi]node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "ERR_BAD_REQUEST".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

2. 上次的导出以后，还要重头导出，希望能够有断点续传功能

**Comment by vannvan** [comment]
> 有几类文档无法导出 1.表格型数据 2. 嵌入附件的文档 3. 其他语雀定义的比较复杂的格式
> 
> 1. 因为有读取不了的场景，这个时候就会直接报错，导致中断，希望能够增加异常处理
>    rror: ENOENT: no such file or directory, open './docs/xxxx.md'
>    at Object.openSync (node:fs:590:3)
>    at Object.writeFileSync (node:fs:2295:35)
>    at File.touch2 (file:///usr/local/lib/node_modules/yuque-tools/dist/lib/file.js:57:12)
>    at Timeout._onTimeout (file:///usr/local/lib/node_modules/yuque-tools/dist/lib/tool.js:245:15)
> 
> 还有 请选择知识库(空格选中--这个是有文件嵌入的 ⠦ 正在导出[xxxxx/it/bi92pi]node:internal/process/promises:289 triggerUncaughtException(err, true /* fromPromise */); ^
> 
> [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "ERR_BAD_REQUEST".] { code: 'ERR_UNHANDLED_REJECTION' }
> 
> 2. 上次的导出以后，还要重头导出，希望能够有断点续传功能

是这样的，语雀目前除了我们在写文档时用标准的Markdown语法之外，其他的文档格式都是私有协议的富文本格式，这个工具其实就是它页面“导出”功能的批量操作版(不过只支持Markdown)，对于私有协议的富文本格式其它工具也是不支持的，就算导出为pdf或其它格式，也不具备其它工具/平台的友好显示功能，同时工具本身是无法识别文档内容是什么格式的(可能多种格式混用的情况，因此对于导出非Markdown类型的文档不在这个工具的设想范围内，此类文档一般会导出失败，工具有生成导出报告，可根据导出报告再去语雀导出为更适合的格式就可以。感谢支持！

**Comment by walker83** [comment]
当前遇到的问题是一旦遇到报错，导出程序就中断了。
软件是否可以改为遇到此类失败，跳过就行？

**Comment by vannvan** [comment]
> 当前遇到的问题是一旦遇到报错，导出程序就中断了。 软件是否可以改为遇到此类失败，跳过就行？

这个可以改进哈哈

**Comment by walker83** [comment]
发现头条已经有人在夸你了：
https://www.toutiao.com/article/7230832211095224869

**Comment by vannvan** [comment]
> 发现头条已经有人在夸你了： https://www.toutiao.com/article/7230832211095224869

哈哈哈哈哈哈哈哈🤣🤣🤣
