### ISSUE TITLE
Error上报/GET请求出错

### ISSUE THREAD

**Issue by jellzone** [vannvan/yuque-tools#40]
Node: 20.12.2 OS: win32
错误信息: AxiosError: Request failed with status code 404,https://www.yuque.com/quicker/help/api/mine/user_books?user_type=Group
Error
    at Object.error (file:///C:/Users/jellz/AppData/Roaming/npm/node_modules/yuque-tools/dist/lib/dev/log.js:8:27)
    at file:///C:/Users/jellz/AppData/Roaming/npm/node_modules/yuque-tools/dist/lib/request.js:63:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

以上信息可删除路径等隐私信息，但需要保留之后的行数哦~

**Comment by vannvan** [comment]
> Node: 20.12.2 OS: win32 错误信息: AxiosError: Request failed with status code 404,https://www.yuque.com/quicker/help/api/mine/user_books?user_type=Group Error at Object.error (file:///C:/Users/jellz/AppData/Roaming/npm/node_modules/yuque-tools/dist/lib/dev/log.js:8:27) at file:///C:/Users/jellz/AppData/Roaming/npm/node_modules/yuque-tools/dist/lib/request.js:63:17 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> 以上信息可删除路径等隐私信息，但需要保留之后的行数哦~

看接口请求你应该是需要导出空间知识库吧，需要配置host才可以，参考[这里](https://github.com/vannvan/yuque-tools/blob/main/packages/yuque-tools-cli/README.md#%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95)

**Comment by jellzone** [comment]
可以了，谢谢，用down 命令搞定
