### ISSUE TITLE
Error上报/GET请求出错

### ISSUE THREAD

**Issue by dwfy** [vannvan/yuque-tools#41]
Node: 20.12.0 OS: win32
错误信息: AxiosError: Request failed with status code 404,https://www.yuque.com////markdown?attachment=true&latexcode=false&anchor=false&linebreak=false
Error
    at Object.error (file:///E:/nodejs/node_global/node_modules/yuque-tools/dist/lib/dev/log.js:8:27)
    at file:///E:/nodejs/node_global/node_modules/yuque-tools/dist/lib/request.js:63:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

以上信息可删除路径等隐私信息，但需要保留之后的行数哦~

**Comment by vannvan** [comment]
> Node: 20.12.0 OS: win32 错误信息: AxiosError: Request failed with status code 404,https://www.yuque.com////markdown?attachment=true&latexcode=false&anchor=false&linebreak=false Error at Object.error (file:///E:/nodejs/node_global/node_modules/yuque-tools/dist/lib/dev/log.js:8:27) at file:///E:/nodejs/node_global/node_modules/yuque-tools/dist/lib/request.js:63:17 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> 以上信息可删除路径等隐私信息，但需要保留之后的行数哦~

ytool clear之后重新试一下流程呢

**Comment by dwfy** [comment]
感谢回复，已经好了。顺便问一下，ytool down 后面的ask格式是什么

**Comment by vannvan** [comment]
> 感谢回复，已经好了。顺便问一下，ytool down 后面的ask格式是什么

ask的含义就是会进入交互式环节，命令行不需要其它参数了😂
