### ISSUE TITLE
小记导出求助

### ISSUE THREAD

**Issue by Hansest** [vannvan/yuque-tools#49]
## 设备信息

Windows11 22H2 64位

## 操作步骤

需求是导出小记。
从使用文档来看，可以在命令行中使用 `ytool pull 18989XXX xxxx note` 命令只导出小记而非知识库文档，但在 Powershell 中的使用体验如下：
![错误图片 1.png](https://s2.loli.net/2024/09/28/tA4NJkeDfZnXYoH.png)
看起来 pull 命令并不支持使用参数？我已反复阅读文档，可能理解还有不到位之处？

另一方面，尝试用“高级用法”中的 json 配置文件达到导出小记的结果，然而在编辑 ` "onlyNote": true,` 之后，命令行交互并无变化，进一步实验发现似乎配置文件并未起作用？（如修改 output 参数并清除缓存后仍未更改保存路径）

现在不清楚该用怎样的方法导出小记呢？

**Comment by vannvan** [comment]
导出小记之需要填写以下几项配置就可以了：

```json
// yuque.config.json
{
  "userName": "xxx",
  "password": "xxx",
  "onlyNote":true
}

```

![Oct-02-2024 21-43-01](https://github.com/user-attachments/assets/d5e5d163-2b75-4378-b5aa-c2f275b29ff5)

**Comment by Hansest** [comment]
从您的演示中得知：本工具在您的 PC 配置上可以正常运行。经过一番对比后认识到可能是版本问题，于是抛弃了 releases 中的可执行程序版而选用了 npm 安装到全局，现在问题已经顺利解决，感谢您的开发！
