### ISSUE TITLE
导出功能小改进

### ISSUE THREAD

**Issue by linxd5** [vannvan/yuque-tools#8]
src/lib/tool.ts第210行`item.type == 'TITLE' && F.mkdir(CONFIG.outputDir + '/' + fullPath)`能否改成`F.mkdir(CONFIG.outputDir + '/' + fullPath)`，即去除`item.type == 'TITLE'`的判断？

语雀并没有限制文档下边不能有子文档，`item.type`的限制会使得文档没法创建目录来保存子文档。

**Comment by vannvan** [comment]
> src/lib/tool.ts第210行`item.type == 'TITLE' && F.mkdir(CONFIG.outputDir + '/' + fullPath)`能否改成`F.mkdir(CONFIG.outputDir + '/' + fullPath)`，即去除`item.type == 'TITLE'`的判断？
> 
> 语雀并没有限制文档下边不能有子文档，`item.type`的限制会使得文档没法创建目录来保存子文档。

已修复https://github.com/vannvan/yuque-tools/issues/9#issue-1718098861
