### ISSUE TITLE
更新记录👉

### ISSUE THREAD

**Issue by vannvan** [vannvan/yuque-tools#9]
## 2023-07-15
- 发布2.0新版本
- 更新记录迁移 👇 
> https://github.com/vannvan/yuque-tools/blob/main/CHANGELOG.md
## 2023-06-23
- 支持保持语雀换行标签选项，`lb`命令行参数和`linebreak`配置

例如:
> ytool pull 18989XXX xxxx 个人日记 其它XXX skip  lb

具体使用方法见:[导出示例](https://github.com/vannvan/yuque-tools#pull-%E5%AF%BC%E5%87%BA)

## 2023-06-17 
- 支持跳过或者覆盖本地已存在文件(跳过的文档会体现在导出报告中)
- 支持一行命令完成导出，不用进入交互环节

例如：
> ytool pull 18989XXX xxxx 个人日记 其它XXX skip   表示导出个人日记 其它XXX这两个知识库并不覆盖本地文件
> ytool pull 18989XXX xxxx all skip 表示导出所有并不覆盖本地文件

具体使用方法见:[导出示例](https://github.com/vannvan/yuque-tools#pull-%E5%AF%BC%E5%87%BA)

## 2023-06-04
新增可执行程序包[v1.0.0-beta](https://github.com/vannvan/yuque-tools/releases/tag/v1.0.0-beta)

### 已解决的issues
- [x] 支持子文档
- [x] 下载时报错不再中断整体进程 

### 目前已支持的知识库结构
测试知识库链接
https://www.yuque.com/vannvan/dd67e4
![](https://p.ipic.vip/iqak6t.png)
以上知识库会生成如下目录：  
![](https://p.ipic.vip/gt8pjs.png)  
以上知识库会生成如下报告：  
![](https://p.ipic.vip/8kmbwg.png)

## TODO
- [x] 支持跳过或者覆盖本地已存在文件
- [x] 其他可能出现错误的环节处理
- [x] 语雀换行可选，因为对于`<br/>`标签有些平台认有些平台不认
- [x] 支持空间级别的知识库导出

**Comment by zanebie** [comment]
大佬你好，我点开yuque-tools.exe的时候直接闪退了，请问是还有什么需要安装的没装吗，谢谢大佬😭

**Comment by vannvan** [comment]
> 大佬你好，我点开yuque-tools.exe的时候直接闪退了，请问是还有什么需要安装的没装吗，谢谢大佬😭

抱歉`gihtub`通知太多才看到，因为我的调试设备有限无法完整覆盖windows的复杂平台环境，所以我暂时也没有很好的办法解决这个问题☹️

**Comment by vannvan** [comment]
> 大佬你好，我点开yuque-tools.exe的时候直接闪退了，请问是还有什么需要安装的没装吗，谢谢大佬😭

抱歉windows的程序
